name: Code-Format-Check

on:
  schedule:
    - cron: '0 21 * * *'
  push:
    branches: [ "main", "triton_v3.2.x" ]
  pull_request:
    branches: [ "main", "triton_v3.2.x" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - uses: pre-commit/action@v3.0.1
